spec:
  structures:
    - content_blocks
  label: Embed
  description: "Embed content from other sources."
  icon: data_object
  tags: []

blueprint:
  src:
  title:
  aspect_ratio: golden

preview:

_inputs:
  src:
    comment: The url source for the iframe
  aspect_ratio:
    comment: The aspect ratio of the embed
    type: select
    options:
      values:
        - square
        - landscape
        - portrait
        - widescreen
        - ultrawide
        - golden
